version: '0.1.{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- |- # Restore TWICE. See https://github.com/AArnott/Nerdbank.GitVersioning/issues/113#issuecomment-285903085
  msbuild RemoteClient.Roslyn.sln /nologo /m /t:restore
  msbuild RemoteClient.Roslyn.sln /nologo /m /v:quiet /t:restore > nul
build_script:
- msbuild RemoteClient.Roslyn.sln /nologo /m /v:minimal /t:build,pack
install:
  nuget sources add -Name corefxlab -Source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
nuget:
  account_feed: true
  project_feed: true
